=== LaibAnis/Medical-XML/projetdss_laib_anis_si_G1/src/dosiermedicaux.dtd
<!ENTITY % sexetype "(homme|femme)">
<!ENTITY % numerotype "(personel|profesionnel)">
<!ENTITY % numerocategorie "(mobile|fix)">
<!ENTITY % emailtype "(personel|profesionnel)">
<!ENTITY % adressetype "(privee|travaille)">
<!ENTITY % lieuxtype "(cabinet|etablissementdesante)">
<!ENTITY % consom "(non|oui|sevree)">
<!ENTITY % documenttype "(imagerie_médicale|résultats_d_analyses|ordonnance_de_pharmacie|certificat)">
<!ENTITY dinar "DA">

<!ELEMENT dossiermidecaux (listemedecin,listepatient,listdossier)>
<!-- Description des medecin-->
<!ELEMENT listemedecin (medecin+)>
<!ELEMENT medecin (informationpersonnel,informationprofesionnel)>
<!ATTLIST medecin idm ID #REQUIRED
sexe %sexetype; #REQUIRED>

<!ELEMENT informationpersonnel (nom,prenom,img,datedenaissance,numero?,email,adresse?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT img EMPTY>
<!ELEMENT datedenaissance (jour,mois,annee)>
<!ELEMENT jour (#PCDATA)>
<!ELEMENT mois (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ATTLIST img src CDATA #REQUIRED> 
<!ELEMENT numero (#PCDATA)>
<!ATTLIST numero type %numerotype; "profesionnel"
categorie %numerocategorie; #IMPLIED>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email type %emailtype; #REQUIRED>
<!ELEMENT adresse (pays?,wilaya,localitee)>
<!ATTLIST adresse type %adressetype; #REQUIRED>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT wilaya (#PCDATA)>
<!ELEMENT localitee (#PCDATA)>

<!ELEMENT informationprofesionnel (specialite,numero,lieuxdetravaille,listediplomme?,listeexperience?)>
<!ELEMENT specialite (#PCDATA)>
<!ELEMENT lieuxdetravaille (lieux+)>
<!ELEMENT lieux (nom,adresse)>
<!ATTLIST lieux type %lieuxtype; #REQUIRED>
<!ELEMENT listediplomme (diplome)>
<!ELEMENT diplome (#PCDATA)>
<!ELEMENT listeexperience (experience)>
<!ELEMENT experience (#PCDATA)>


<!-- Description des patient-->
<!ELEMENT listepatient (patient+)>
<!ELEMENT patient (nom,prenom,img,datedenaissance,age,email?,numero?,adresse)>
<!ATTLIST patient idp ID #REQUIRED
sexe %sexetype; #REQUIRED>
<!ELEMENT age (#PCDATA)>

<!-- Description des dossier-->
<!ELEMENT listdossier (dossier*)>
<!ELEMENT dossier (medecintraitant,informationadministrative,listeconsultation,listantecedant,listeallergie,modedevie,donneedesuivie,carnetvaccination,listetraitementdefond,listetraitementponctuel,listedocument,listobservationmedicale)>
<!ATTLIST dossier idd ID #REQUIRED>

 <!-- la balise <medecintraitant> fait referance grace aux ID , a de tout les medecins qui ont traitee ce dossier et qui se trouve dans la balise <listemedecin> -->
<!ELEMENT medecintraitant EMPTY>
<!ATTLIST medecintraitant ref IDREFS #REQUIRED>

<!ELEMENT informationadministrative (patientconcernee,datedecreation)>
<!-- la balise <patientconcernee> fait referance grace a l'attribut ref , aux ID du patient a qui ce dossier appartient et qui se trouve dans la balise <patientconcernee> -->
<!ELEMENT patientconcernee EMPTY>
<!ATTLIST patientconcernee ref IDREF #REQUIRED>
<!ELEMENT datedecreation (jour,mois,annee)>

<!ELEMENT listeconsultation (consultation+)>
<!ELEMENT consultation (mantant)>
<!ATTLIST consultation id ID #REQUIRED>
<!ELEMENT mantant (#PCDATA)>

<!ELEMENT listantecedant (antecedantmedicaux,antecedantchurigicaux,antecedantfamiliaux)>
<!ELEMENT antecedantmedicaux (pasdantecedant|antecedant+)>

<!ELEMENT pasdantecedant EMPTY>
<!ELEMENT antecedant (nom,parent?,commentaire?,annee)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT commentaire (#PCDATA)>

<!ELEMENT antecedantchurigicaux (pasdantecedant|antecedant+)>

<!ELEMENT antecedantfamiliaux (pasdantecedant|antecedant+)>

<!ELEMENT listeallergie (pasdallergie|allergie+)>

<!ELEMENT pasdallergie EMPTY>
<!ELEMENT allergie (nom,commentaire?,annee)>

<!ELEMENT modedevie (tabac,alcool,profession,autreinformation?)>
<!ELEMENT tabac EMPTY>
<!ATTLIST tabac consomation %consom; #REQUIRED>
<!ELEMENT alcool EMPTY>
<!ATTLIST alcool consomation %consom; #REQUIRED>
<!ELEMENT profession (#PCDATA)>
<!ELEMENT autreinformation (#PCDATA)>


<!ELEMENT donneedesuivie (taille,poids,imc,pressionAS,pressionAD,frequencecardiaque,autredonnee?)>
<!ELEMENT taille (#PCDATA)>
<!ELEMENT poids (#PCDATA)>
<!ELEMENT imc (#PCDATA)>
<!ELEMENT  pressionAS (#PCDATA)>
<!ELEMENT pressionAD (#PCDATA)>
<!ELEMENT frequencecardiaque (#PCDATA)>
<!ELEMENT autredonnee ANY>

<!ELEMENT carnetvaccination (vaccin+)>
<!ELEMENT vaccin (nom,annee,age)>


<!ELEMENT listetraitementdefond (traitement*)>
<!ELEMENT traitement (nom,commentaire?)>
<!ATTLIST traitement idconsultation IDREF #IMPLIED
refordonnance IDREF #IMPLIED
>

<!ELEMENT listetraitementponctuel (traitement+)>


<!ELEMENT listedocument (document+)>
<!ELEMENT document (nom,emeteur)>
<!ATTLIST document ide ID #REQUIRED
src CDATA #REQUIRED
type %documenttype; #REQUIRED
idconsultation IDREF #IMPLIED
>
<!ELEMENT emeteur (#PCDATA)>
<!ATTLIST emeteur ref IDREF #REQUIRED>


<!ELEMENT listobservationmedicale (observationmedical+)>
<!ELEMENT observationmedical (motif,interogatoire,examen)>
<!ATTLIST observationmedical ido ID #REQUIRED
idconsultation IDREF #REQUIRED>
<!ELEMENT motif (#PCDATA)>
<!ELEMENT interogatoire (#PCDATA)>
<!ELEMENT examen (#PCDATA)>

=== LaibAnis/Medical-XML/projetdss_laib_anis_si_G1/build/classes/dossiermedicaux_withDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
 <!DOCTYPE dossiermidecaux SYSTEM "./dosiermedicaux.dtd"> 
<dossiermidecaux >
    <!-- dans cette balise <listemedecin> on definit tout les medecin qui ont traitee un dossier medical et ont leur attribue un ID pour on puisse les réferencier dans le documment -->
    <listemedecin>

        <medecin idm="m_1" sexe="homme">
            <informationpersonnel>
                <nom>Belkaid</nom>
                <prenom>Sofiane</prenom>
                <img src="src//doc1.jpg"/>

                <datedenaissance>
                    <jour>17</jour>
                    <mois>01</mois>
                    <annee>1990</annee>
                </datedenaissance>

                <email type="personel">belsofiane17@gmail.com</email>

                <adresse type="privee">
                    <pays>algerie</pays>
                    <wilaya>oran</wilaya>
                    <localitee>M9V5+VGC, Boulevard Doctor Benzerdjeb, Oran</localitee>
                </adresse>

            </informationpersonnel>

            <informationprofesionnel>
                <specialite>Cardiologie</specialite>
                <numero categorie="mobile">0660917888</numero>
                <lieuxdetravaille>
                    <lieux type="cabinet">
                        <nom>cabinet medicale de dr belkaid</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>5 Place des Victoires, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                    <lieux type="etablissementdesante">
                        <nom>clinique medicale de maternitee </nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>74 Boulevard centre ville, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                </lieuxdetravaille>
            </informationprofesionnel>
        </medecin>

        <medecin idm="m_2" sexe="homme">
            <informationpersonnel>
                <nom>senhadji</nom>
                <prenom>amine</prenom>
                <img src="src//doc2.jpg"/>

                <datedenaissance>
                    <jour>25</jour>
                    <mois>04</mois>
                    <annee>1969</annee>
                </datedenaissance>

                <email type="personel">senham25@gmail.com</email>

                <adresse type="privee">
                    <pays>algerie</pays>
                    <wilaya>oran</wilaya>
                    <localitee>M9V5+VGC, Residence hasnaoui, Oran</localitee>
                </adresse>

            </informationpersonnel>

            <informationprofesionnel>
                <specialite>Ophtalmologie</specialite>
                <numero categorie="mobile">0560917890</numero>
                <lieuxdetravaille>
                    <lieux type="cabinet">
                        <nom>cabinet medicale de dr senhadji</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>5 Place des Victoires, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                    <lieux type="etablissementdesante">
                        <nom>clinique medicale </nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>74 Boulevard Doctor Benzerdjeb, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                </lieuxdetravaille>
            </informationprofesionnel>
        </medecin>

        <medecin idm="m_3" sexe="homme">
            <informationpersonnel>
                <nom>hamedi</nom>
                <prenom>ahmed</prenom>
                <img src="src//doc3.jpg"/>

                <datedenaissance>
                    <jour>20</jour>
                    <mois>08</mois>
                    <annee>1970</annee>
                </datedenaissance>

                <email type="personel">hamediah17@gmail.com</email>

                <adresse type="privee">
                    <pays>algerie</pays>
                    <wilaya>oran</wilaya>
                    <localitee>M9V5+VGC, Boulevard Doctor Benzerdjeb, Oran</localitee>
                </adresse>

            </informationpersonnel>

            <informationprofesionnel>
                <specialite>Oncologie</specialite>
                <numero categorie="mobile">0760917800</numero>
                <lieuxdetravaille>
                    <lieux type="cabinet">
                        <nom>cabinet medicale de dr hamedi</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>5 Place des Victoires, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                    <lieux type="etablissementdesante">
                        <nom>clinique medicale</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>74 Boulevard Doctor Benzerdjeb, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                </lieuxdetravaille>
            </informationprofesionnel>
        </medecin>
        
        <medecin idm="m_4" sexe="homme">
            <informationpersonnel>
                <nom>zemouri</nom>
                <prenom>marwane</prenom>
                <img src="src//doc4.jpg"/>

                <datedenaissance>
                    <jour>18</jour>
                    <mois>07</mois>
                    <annee>1980</annee>
                </datedenaissance>

                <email type="personel">zmmarwane18@gmail.com</email>

                <adresse type="privee">
                    <pays>algerie</pays>
                    <wilaya>oran</wilaya>
                    <localitee>M9V5+VGC, Senia, Oran</localitee>
                </adresse>

            </informationpersonnel>

            <informationprofesionnel>
                <specialite>Oncologie</specialite>
                <numero categorie="mobile">0790817700</numero>
                <lieuxdetravaille>
                    <lieux type="cabinet">
                        <nom>cabinet medicale de dr hamedi</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>5 Place des Victoires, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                    <lieux type="etablissementdesante">
                        <nom>clinique medicale</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>74 Boulevard Doctor Benzerdjeb, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                </lieuxdetravaille>
            </informationprofesionnel>
        </medecin>
        
        <medecin idm="m_5" sexe="femme">
            <informationpersonnel>
                <nom>Melianni</nom>
                <prenom>Oumayma</prenom>
                <img src="src//doc5.jpg"/>

                <datedenaissance>
                    <jour>8</jour>
                    <mois>10</mois>
                    <annee>1985</annee>
                </datedenaissance>

                <email type="personel">meoumatma18@gmail.com</email>

                <adresse type="privee">
                    <pays>algerie</pays>
                    <wilaya>oran</wilaya>
                    <localitee>M9V5+VGC, Fernanville, Oran</localitee>
                </adresse>

            </informationpersonnel>

            <informationprofesionnel>
                <specialite>Oncologie</specialite>
                <numero categorie="mobile">0678811800</numero>
                <lieuxdetravaille>
                    <lieux type="cabinet">
                        <nom>cabinet medicale de Melianni</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>Centre ville, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                    <lieux type="etablissementdesante">
                        <nom>clinique medicale</nom>
                        <adresse type="travaille">
                            <pays>algerie</pays>
                            <wilaya>oran</wilaya>
                            <localitee>74 Boulevard Doctor Benzerdjeb, Oran 31000</localitee>
                        </adresse>
                    </lieux>
                </lieuxdetravaille>
            </informationprofesionnel>
        </medecin>
        

    </listemedecin>

     <!-- dans cette balise <listepatient> on definit tout les patient qui ont eté traitee avec un dossier medical et ont leur attribue un ID pour on puisse les réferencier dans le documment -->

    <listepatient>

        <patient idp="p_1" sexe="femme">
